const products = [
    // Thiết bị điện tử
    {
        id: 1,
        category: 'Thiết bị điện tử',
        name: 'Iphone 6',
        brand: 'Apple',
        price: '29.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone6.jpg',
        place: 'Hà Nội',
        sold: 30,
    },
    {
        id: 2,
        category: 'Thiết bị điện tử',
        name: 'Iphone 6 Plus',
        brand: 'Apple',
        price: '3.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone6plus.jpg',
        place: 'Hà Nội',
        sold: 500,
    },
    {
        id: 3,
        category: 'Thiết bị điện tử',
        name: 'Iphone 7',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone7.jpg',
        place: 'Hà Nội',
        sold: 500,
    },
    {
        id: 4,
        category: 'Thiết bị điện tử',
        name: 'Iphone 7 Plus',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone7plus.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 5,
        category: 'Thiết bị điện tử',
        name: 'Iphone 8',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone8.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 6,
        category: 'Thiết bị điện tử',
        name: 'Iphone 8 Plus',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone8plus.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 7,
        category: 'Thiết bị điện tử',
        name: 'Iphone X',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphonex.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 8,
        category: 'Thiết bị điện tử',
        name: 'Iphone Xr',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphonexr.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 9,
        category: 'Thiết bị điện tử',
        name: 'Iphone Xs',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphonexs.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 10,
        category: 'Thiết bị điện tử',
        name: 'Iphone Xs Max',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphonexsmax.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 11,
        category: 'Thiết bị điện tử',
        name: 'Iphone 11',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone11.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 12,
        category: 'Thiết bị điện tử',
        name: 'Iphone 11 Pro',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone11pro.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 13,
        category: 'Thiết bị điện tử',
        name: 'Iphone 11 Pro Max',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone11promax.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 14,
        category: 'Thiết bị điện tử',
        name: 'Iphone 12 Mini',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone12mini.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 15,
        category: 'Thiết bị điện tử',
        name: 'Iphone 12',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone12.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 16,
        category: 'Thiết bị điện tử',
        name: 'Iphone 12 Pro',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone12pro.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    {
        id: 17,
        category: 'Thiết bị điện tử',
        name: 'Iphone 12 Pro Max',
        brand: 'Apple',
        price: '35.000.000đ',
        image: 'images/products/ThietBiDienTu/iphone11promax.jpg',
        place: 'Hà Nội',
        sold: 48,
    },
    // Sách
    {
        id: 18,
        category: 'Sách',
        name: 'Hoàng tử bé',
        brand: '',
        price: '53.700đ',
        image: 'images/products/Sach/HoangTuBe.jpg',
        place: 'Hà Nội',
        sold: 6981,
    },
    {
        id: 19,
        category: 'Sách',
        name: 'Muôn kiếp nhân sinh',
        brand: '',
        price: '109.000đ',
        image: 'images/products/Sach/MuonKiepNhanSinh.jpg',
        place: 'Hà Nội',
        sold: 4169,
    },
    {
        id: 20,
        category: 'Sách',
        name: 'Nhà giả kim',
        brand: '',
        price: '55.000đ',
        image: 'images/products/Sach/NhaGiaKim.jpg',
        place: 'Hồ Chí Minh',
        sold: 9654,
    },
    {
        id: 21,
        category: 'Sách',
        name: 'Tôi tự học',
        brand: '',
        price: '32.900đ',
        image: 'images/products/Sach/ToiTuHoc.jpg',
        place: 'Đà nẵng',
        sold: 2456,
    },
    {
        id: 22,
        category: 'Sách',
        name: 'Đắc nhân tâm',
        brand: '',
        price: '56.100đ',
        image: 'images/products/Sach/DacNhanTam.jpg',
        place: 'Hà Nội',
        sold: 16498,
    },
    {
        id: 23,
        category: 'Sách',
        name: 'Mắt biếc',
        brand: '',
        price: '76.400đ',
        image: 'images/products/Sach/MatBiec.jpg',
        place: 'Nghệ An',
        sold: 9543,
    },
    {
        id: 24,
        category: 'Sách',
        name: 'Không gia đình',
        brand: '',
        price: '74.500đ',
        image: 'images/products/Sach/KhongGiaDinh.jpg',
        place: 'Hà Nội',
        sold: 12483,
    },
    {
        id: 25,
        category: 'Sách',
        name: 'Your name',
        brand: '',
        price: '45.000đ',
        image: 'images/products/Sach/YourName.jpg',
        place: 'Hồ Chí Minh',
        sold: 5347,
    },
    {
        id: 26,
        category: 'Sách',
        name: 'Hai số phận',
        brand: '',
        price: '97.900đ',
        image: 'images/products/Sach/HaiSoPhan.jpg',
        place: 'Hà Nội',
        sold: 1452,
    },
    {
        id: 27,
        category: 'Sách',
        name: 'Đi tìm lẽ sống',
        brand: '',
        price: '61.900đ',
        image: 'images/products/Sach/DiTimLeSong.jpg',
        place: 'Hà Nội',
        sold: 2486,
    },
    // Thời trang
    {
        id: 28,
        category: 'Thời trang',
        name: 'Áo phông',
        brand: 'Nike',
        price: '919.000đ',
        image: 'images/products/ThoiTrang/ao1.jpg',
        place: 'Hà Nội',
        sold: 541,
    },
    {
        id: 29,
        category: 'Thời trang',
        name: 'Áo phông',
        brand: 'Nike',
        price: '719.000đ',
        image: 'images/products/ThoiTrang/ao2.jpg',
        place: 'Hà Nội',
        sold: 349,
    },
    {
        id: 30,
        category: 'Thời trang',
        name: 'Áo khoác',
        brand: 'Nike',
        price: '2.499.000đ',
        image: 'images/products/ThoiTrang/ao3.jpg',
        place: 'Hồ Chí Minh',
        sold: 684,
    },
    {
        id: 31,
        category: 'Thời trang',
        name: 'Quần nỉ họa tiết',
        brand: 'Nike',
        price: '2.299.000đ',
        image: 'images/products/ThoiTrang/quan1.jpg',
        place: 'Hà Nội',
        sold: 246,
    },
    {
        id: 32,
        category: 'Thời trang',
        name: 'Quần nỉ đen sọc trắng',
        brand: 'Nike',
        price: '1.759.000đ',
        image: 'images/products/ThoiTrang/quan2.jpg',
        place: 'Hà Nội',
        sold: 694,
    },
    {
        id: 33,
        category: 'Thời trang',
        name: 'Áo phông',
        brand: 'Nike',
        price: '1.479.000đ',
        image: 'images/products/ThoiTrang/ao4.jpg',
        place: 'Hà Nội',
        sold: 614,
    },
    {
        id: 34,
        category: 'Thời trang',
        name: 'Quần nỉ Jordan',
        brand: 'Nike',
        price: '1.919.000đ',
        image: 'images/products/ThoiTrang/quan3.jpg',
        place: 'Hà Nội',
        sold: 537,
    },
    {
        id: 35,
        category: 'Thời trang',
        name: 'Áo phông',
        brand: 'Nike',
        price: '819.000đ',
        image: 'images/products/ThoiTrang/ao5.jpg',
        place: 'Hồ Chí Minh',
        sold: 769,
    },
    {
        id: 36,
        category: 'Thời trang',
        name: 'Quần đùi',
        brand: 'Nike',
        price: '659.000đ',
        image: 'images/products/ThoiTrang/quan6.jpg',
        place: 'Hà Nội',
        sold: 426,
    },
    {
        id: 37,
        category: 'Thời trang',
        name: 'Quần nỉ xám',
        brand: 'Nike',
        price: '1.019.000đ',
        image: 'images/products/ThoiTrang/quan5.jpg',
        place: 'Hà Nội',
        sold: 418,
    },
    {
        id: 38,
        category: 'Thời trang',
        name: 'Áo khoác',
        brand: 'Nike',
        price: '1.739.000đ',
        image: 'images/products/ThoiTrang/ao6.jpg',
        place: 'Hà Nội',
        sold: 849,
    },
    {
        id: 39,
        category: 'Thời trang',
        name: 'Quần đùi',
        brand: 'Nike',
        price: '659.000đ',
        image: 'images/products/ThoiTrang/quan7.jpg',
        place: 'Hồ Chí Minh',
        sold: 968,
    },
    // Đồ tiêu dùng
    {
        id: 40,
        category: 'Đồ tiêu dùng',
        name: 'Nước xả vải Comfort',
        brand: '',
        price: '145.000đ',
        image: 'images/products/DoTieuDung/comfort.jpg',
        place: 'Hồ Chí Minh',
        sold: 6514,
    },
    {
        id: 41,
        category: 'Đồ tiêu dùng',
        name: 'Thùng bia Tiger',
        brand: '',
        price: '341.000đ',
        image: 'images/products/DoTieuDung/BiaTiger.jpg',
        place: 'Hồ Chí Minh',
        sold: 3145,
    },
    {
        id: 42,
        category: 'Đồ tiêu dùng',
        name: 'Thùng mỳ tôm Hảo Hảo',
        brand: '',
        price: '108.000đ',
        image: 'images/products/DoTieuDung/haohao.jpg',
        place: 'Hồ Chí Minh',
        sold: 14905,
    },
    {
        id: 43,
        category: 'Đồ tiêu dùng',
        name: 'Dầu đậu nành Simply',
        brand: '',
        price: '108.000đ',
        image: 'images/products/DoTieuDung/DauAn.jpg',
        place: 'Hồ Chí Minh',
        sold: 12450,
    },
    {
        id: 44,
        category: 'Đồ tiêu dùng',
        name: 'Thùng bia Heineken ',
        brand: '',
        price: '405.000đ',
        image: 'images/products/DoTieuDung/BiaHeineken.jpg',
        place: 'Hồ Chí Minh',
        sold: 6843,
    },
    {
        id: 45,
        category: 'Đồ tiêu dùng',
        name: 'Lốc 4 hộp sữa Nestle Milo',
        brand: '',
        price: '28.000đ',
        image: 'images/products/DoTieuDung/milo.jpg',
        place: 'Hồ Chí Minh',
        sold: 9421,
    },
    {
        id: 46,
        category: 'Đồ tiêu dùng',
        name: 'Túi nước giặt Omo Matic',
        brand: '',
        price: '142.000đ',
        image: 'images/products/DoTieuDung/omo.jpg',
        place: 'Hồ Chí Minh',
        sold: 3457,
    },
    {
        id: 47,
        category: 'Đồ tiêu dùng',
        name: 'Thùng 48 hộp sữa tươi có đường TH True Milk',
        brand: '',
        price: '259.000đ',
        image: 'images/products/DoTieuDung/suaTH.jpg',
        place: 'Hồ Chí Minh',
        sold: 2496,
    },
    {
        id: 48,
        category: 'Đồ tiêu dùng',
        name: 'Nước rửa chén Sunlight',
        brand: '',
        price: '91.000đ',
        image: 'images/products/DoTieuDung/sunlight.jpg',
        place: 'Hồ Chí Minh',
        sold: 3516,
    },
    {
        id: 49,
        category: 'Đồ tiêu dùng',
        name: 'Nước tẩy bồn cầu Vim',
        brand: '',
        price: '36.000đ',
        image: 'images/products/DoTieuDung/vim.jpg',
        place: 'Hồ Chí Minh',
        sold: 3475,
    },
    

]